// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/signal/v1/signal.proto

package signalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signal represents a single trade signal.
type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_proto_signal_v1_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_v1_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_proto_signal_v1_signal_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Signal) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Signal) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Signal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CreateSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Price         uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSignalRequest) Reset() {
	*x = CreateSignalRequest{}
	mi := &file_proto_signal_v1_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignalRequest) ProtoMessage() {}

func (x *CreateSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_v1_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignalRequest.ProtoReflect.Descriptor instead.
func (*CreateSignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_v1_signal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSignalRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateSignalRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateSignalRequest) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *Signal                `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSignalResponse) Reset() {
	*x = CreateSignalResponse{}
	mi := &file_proto_signal_v1_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSignalResponse) ProtoMessage() {}

func (x *CreateSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_v1_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSignalResponse.ProtoReflect.Descriptor instead.
func (*CreateSignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_signal_v1_signal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSignalResponse) GetSignal() *Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type GetSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalsRequest) Reset() {
	*x = GetSignalsRequest{}
	mi := &file_proto_signal_v1_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalsRequest) ProtoMessage() {}

func (x *GetSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_v1_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalsRequest.ProtoReflect.Descriptor instead.
func (*GetSignalsRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_v1_signal_proto_rawDescGZIP(), []int{3}
}

type GetSignalsBySymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalsBySymbolRequest) Reset() {
	*x = GetSignalsBySymbolRequest{}
	mi := &file_proto_signal_v1_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalsBySymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalsBySymbolRequest) ProtoMessage() {}

func (x *GetSignalsBySymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_v1_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalsBySymbolRequest.ProtoReflect.Descriptor instead.
func (*GetSignalsBySymbolRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_v1_signal_proto_rawDescGZIP(), []int{4}
}

func (x *GetSignalsBySymbolRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalsResponse) Reset() {
	*x = GetSignalsResponse{}
	mi := &file_proto_signal_v1_signal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalsResponse) ProtoMessage() {}

func (x *GetSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_v1_signal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalsResponse.ProtoReflect.Descriptor instead.
func (*GetSignalsResponse) Descriptor() ([]byte, []int) {
	return file_proto_signal_v1_signal_proto_rawDescGZIP(), []int{5}
}

func (x *GetSignalsResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

var File_proto_signal_v1_signal_proto protoreflect.FileDescriptor

const file_proto_signal_v1_signal_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/signal/v1/signal.proto\x12\tsignal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n" +
	"\x06Signal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"[\n" +
	"\x13CreateSignalRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\"A\n" +
	"\x14CreateSignalResponse\x12)\n" +
	"\x06signal\x18\x01 \x01(\v2\x11.signal.v1.SignalR\x06signal\"\x13\n" +
	"\x11GetSignalsRequest\"3\n" +
	"\x19GetSignalsBySymbolRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"A\n" +
	"\x12GetSignalsResponse\x12+\n" +
	"\asignals\x18\x01 \x03(\v2\x11.signal.v1.SignalR\asignals2\x86\x02\n" +
	"\rSignalService\x12O\n" +
	"\fCreateSignal\x12\x1e.signal.v1.CreateSignalRequest\x1a\x1f.signal.v1.CreateSignalResponse\x12I\n" +
	"\n" +
	"GetSignals\x12\x1c.signal.v1.GetSignalsRequest\x1a\x1d.signal.v1.GetSignalsResponse\x12Y\n" +
	"\x12GetSignalsBySymbol\x12$.signal.v1.GetSignalsBySymbolRequest\x1a\x1d.signal.v1.GetSignalsResponseB=Z;github.com/Atharva0506/trading_bot/proto/signal/v1;signalpbb\x06proto3"

var (
	file_proto_signal_v1_signal_proto_rawDescOnce sync.Once
	file_proto_signal_v1_signal_proto_rawDescData []byte
)

func file_proto_signal_v1_signal_proto_rawDescGZIP() []byte {
	file_proto_signal_v1_signal_proto_rawDescOnce.Do(func() {
		file_proto_signal_v1_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signal_v1_signal_proto_rawDesc), len(file_proto_signal_v1_signal_proto_rawDesc)))
	})
	return file_proto_signal_v1_signal_proto_rawDescData
}

var file_proto_signal_v1_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_signal_v1_signal_proto_goTypes = []any{
	(*Signal)(nil),                    // 0: signal.v1.Signal
	(*CreateSignalRequest)(nil),       // 1: signal.v1.CreateSignalRequest
	(*CreateSignalResponse)(nil),      // 2: signal.v1.CreateSignalResponse
	(*GetSignalsRequest)(nil),         // 3: signal.v1.GetSignalsRequest
	(*GetSignalsBySymbolRequest)(nil), // 4: signal.v1.GetSignalsBySymbolRequest
	(*GetSignalsResponse)(nil),        // 5: signal.v1.GetSignalsResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_proto_signal_v1_signal_proto_depIdxs = []int32{
	6, // 0: signal.v1.Signal.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: signal.v1.CreateSignalResponse.signal:type_name -> signal.v1.Signal
	0, // 2: signal.v1.GetSignalsResponse.signals:type_name -> signal.v1.Signal
	1, // 3: signal.v1.SignalService.CreateSignal:input_type -> signal.v1.CreateSignalRequest
	3, // 4: signal.v1.SignalService.GetSignals:input_type -> signal.v1.GetSignalsRequest
	4, // 5: signal.v1.SignalService.GetSignalsBySymbol:input_type -> signal.v1.GetSignalsBySymbolRequest
	2, // 6: signal.v1.SignalService.CreateSignal:output_type -> signal.v1.CreateSignalResponse
	5, // 7: signal.v1.SignalService.GetSignals:output_type -> signal.v1.GetSignalsResponse
	5, // 8: signal.v1.SignalService.GetSignalsBySymbol:output_type -> signal.v1.GetSignalsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_signal_v1_signal_proto_init() }
func file_proto_signal_v1_signal_proto_init() {
	if File_proto_signal_v1_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signal_v1_signal_proto_rawDesc), len(file_proto_signal_v1_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signal_v1_signal_proto_goTypes,
		DependencyIndexes: file_proto_signal_v1_signal_proto_depIdxs,
		MessageInfos:      file_proto_signal_v1_signal_proto_msgTypes,
	}.Build()
	File_proto_signal_v1_signal_proto = out.File
	file_proto_signal_v1_signal_proto_goTypes = nil
	file_proto_signal_v1_signal_proto_depIdxs = nil
}
