package mocks

// TODO: Automatic Mocks generated by tools like `mockery`
// Responsibilities:
// - Provides fake structures mapping precisely to Interface definitions
// - Simulates external system collapses safely so isolated unit tests execute quickly without the network
