# TODO: Centralized commands
# Responsibilities:
# - Define `run`, `build`, `test`, `lint`, and `docker-up` targets
# - Ensure running `make test` executes both unit and integration tests

.PHONY: run build test lint

run:
	# Implementation goes here

build:
	# Implementation goes here

test:
	# Implementation goes here
